[package]
name = "dashboard-motd"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-unit = "5.1.4"
clap = "4.5.18"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
dirs = "5.0.1"
regex = "1.11.0"
libc = "0.2.159"
serde_json = "1.0.128"
humantime = "2.1.0"
